### ISSUE TITLE
Homework: create a Issue and comment about something learned in clases.

### ISSUE THREAD

**Issue by jivarelao** [jivarelao/course_notes#1]
@cecileane
@coraallencoleman
## Interesting things learned at STAT679 - Fall 2018

The course so far has been of great utility for myself, I've been really interested in the power of bash.\
In fact I used the bash command line to create a code using regular expressions to find and replace\
 raw genotypic data for my own research. To accomplish this task I applied two very important skills\
 learned in the course: `loops` and `grep`. This was instrumental to perform the objective fast.\
In fact I am so happy with the results that I want to compare the speed of this task done in R vs done in Bash.\
It's been very interesting so far.

If you want to learn about `loops` you can visit [here](http://swcarpentry.github.io/shell-novice/05-loop/index.html).  
If you want to learn about `grep` you can visit [here](http://swcarpentry.github.io/shell-novice/07-find/index.html).

Thanks\
**Jose**

**Comment by cecileane** [comment]
this is so great to hear. thanks!
