### ISSUE TITLE
Homework 4 Jose Varela  

### ISSUE THREAD

**Issue by jivarelao** [jivarelao/course_notes#2]
@cecileane
@coraallencoleman
## Part 1 : Find and replace using `sed`
To remove the **commas** and the **quotes** I would use the following command:\
\
`sed -E 's/(".*),(.*")/\1\2/g' tableofSNPs.csv | sed -E 's/(".*),(.*")/\1\2/g' | sed 's/"//g' > tableofSNPs_clean.csv`\
\
This command line works OK for the file of this exercise, it looks for one or two commas inside\
the quotes and returns everything except the commas. The first part (before the pipe) remove\
the first comma inside the quotes, then after the pipe remove the second comma (if there is any).\
Finally, after the second pipe `sed` replaces the quotes with nothing (removes them). In case there\
were more than 2 commas inside the quotes the following code **(check)** line would detect that,\
and if that was case we should add a third pipe and re-run the code, but this is not the case.\
The code will generate an output file: **tableofSNPs_clean.csv** which will be the input for the next\
section.
## Part 1.2 : Checking the output

After completing part 1 The following line checks that there are exactly 3 commas per line in the\
output file: **tableofSNPs_clean.csv**.\
\
`sed -E 's/[^,]//g' tableofSNPs_clean.csv | uniq`  
\
This command will remove anything except commas and then show the unique lines. If everything is\
correct it should only show as result one line with 3 commas. Any line with less or more than 3\
commas will show up as another unique line. Furthermore we can add an extra pipe with `wc` and\
check through count (output will depend on the flag after `wc`). If everything is OK it should find\
one word, one line and three characters.

## Part 2:

The following `sed` command will replace all the 'A' s for 'T's and 'T's for 'A' in a logical order using\
temporary substitutes to avoid replacing mistakes and will generate a new output file:\
**tableofSNPs_clean_nucleotides_corrected.csv**.

`sed -e 's/A/X/g' tableofSNPs_clean.csv | sed -e 's/T/A/g' | sed -e 's/X/T/g' > tableofSNPs_clean_nucleotides_corrected.csv`

## Part 2.1: check

One simple way to check this one-liner would be to use `grep` command and count the nucleotides\
in the original file (**tableofSNPs.csv**) and compare the count to the count of corrected\
nucleotides of the output of part two **tableofSNPs_clean_nucleotides_corrected.csv**.\
The count of 'A's in **tableofSNPs.csv** should be equal to the count of 'T's in\
**tableofSNPs_clean_nucleotides_corrected.csv**, the count of 'T's in **tableofSNPs.csv**\
should be equal to the count of 'A's in **tableofSNPs_clean_nucleotides_corrected.csv**.\
The count of 'C's and 'G' s shoul be equal for both.\
We can perform this using two simple loops:\
\
`NUCLEO_PERM='A T C G'`\
`NUCLEO_OK='T A C G'`\
``for N in $NUCLEO_PERM; do echo $N `grep -c $N tableofSNPs.csv`; done``\
``for N in $NUCLEO_OK; do echo $N `grep -c $N tableofSNPs_clean_nucleotides_corrected.csv`; done``\
\
Thanks\
**Jose**

**Comment by cecileane** [comment]
fantastic Jose!
